### ISSUE TITLE
hello,where the paper is?

### ISSUE THREAD

**Issue by OvOYu** [wudi2001/STGAGRTN#1]

**Comment by wudi2001** [comment]
Sorry, my paper is still under review and not yet available for publication. Currently, only the code has been opened for public access.

**Comment by OvOYu** [comment]
Thank you for your reply, can you upload the model structure diagram first?

**Comment by wudi2001** [comment]
Sorry, I cannot upload the structure diagram before the paper has been published. The model in this paper is easy to understand, and the core modules are organized in a serial manner. I think if you read the code carefully, you will get my central ideas. **Good luck!**

**Comment by OvOYu** [comment]
OK. Good luck！
