### ISSUE TITLE
One question: 8:1:1

### ISSUE THREAD

**Issue by OvOYu** [wudi2001/STGAGRTN#2]
Congratulations on a job well done, there is one question I don't understand, why is it divided on an 811 scale

**Comment by wudi2001** [comment]
Thank you for your interest in our research. The division ratio of datasets can be specified arbitrarily. This code uses an 8:1:1 ratio, but you can also use other ratios as needed. This work has been published in the **IEEE Internet of Things Journal**, and the introductory section about the model can be found in the paper.

D. Wu, K. Peng, S. Wang and V. C. M. Leung, "Spatial-Temporal Graph Attention Gated Recurrent Transformer Network for Traffic Flow Forecasting," in IEEE Internet of Things Journal, doi: 10.1109/JIOT.2023.3340182.

**Comment by OvOYu** [comment]
Thank you for your reply.Wish you all the best!

**Comment by OvOYu** [comment]
你好，我想再问一个问题。因为并不是按照12预测12,而是36预测6，那么文章的所有基线都要36预测6，这样的话很好复现其他base是不是有点困难

**Comment by wudi2001** [comment]
要改输入与输出格式，重新跑一遍模型，有些不提供模型的还要跟作者联系。所以现在很多人都是尽量跟别人论文的输入输出格式对齐，直接copy baseline。

**Comment by OvOYu** [comment]
哈哈 我也觉得 那你觉得如果36到12 和12到12的 在622的划分比   这样行不行 我感觉行又不行的

**Comment by wudi2001** [comment]
可以具体做一下实验，这个跟数据集模型都有关系。当然常规来说，肯定是输入越多，预测越少越精准，即已知信息越多，预测数据越少。至于划分数据集，其实这不是重点，622,811区别不大，622说白了就是训练集少一点，验证集多了。

**Comment by OvOYu** [comment]
感谢您的回复 我就是怕36的输入 相比12的工作 会更多 审稿人针对这一点就不太好回复 除非base都是36到12

**Comment by wudi2001** [comment]
这个问题应该不大，审稿人着重看重的还是待解决的问题，创新点与实验充分不充分。你说的那个因素不大关心，我这篇论文一审就是说待解决的痛点描述不清晰，创新点不清晰，实验不充分。而且我看很多论文根本就不说输入输出时间步多少。

**Comment by OvOYu** [comment]
感谢您的回复 哈哈 你的阵容太强大了 没fellow不敢ieee系列

**Comment by OvOYu** [comment]
一个省的wudi铁子 你是phd了已经还是打算申 你这一篇985很好去

**Comment by wudi2001** [comment]
哎，也多亏了导师。fellow是导师的导师。要不我也不可能认识fellow。

**Comment by wudi2001** [comment]
大四申保研的时候还没这篇论文加持，所以只能考研，现在在等结果，准备去中科院。

**Comment by wudi2001** [comment]
不过我不是福建的，哈哈哈。只是在那边上学，我山东人。也祝你论文早日中稿。

**Comment by OvOYu** [comment]
祝好哈哈 很优秀 期待你的好消息！

**Comment by OvOYu** [comment]
早上好，吴同学！想请问下您处理原始csv和npz数据的脚本，因为我想处理下3和7数据！或者您能提供下处理好的3和7数据吗，感谢！我将在我的文章（小修）中引用您出色的工作！

**Comment by wudi2001** [comment]
不好意思，同学。PEMS03与PEMS07数据是在大修中补充的实验，当时训练完后就直接删除了。我这边也没有对应数据了。但我印象中PEMS原始数据集是没有日期属性的，我在原始下载的数据中添加完以后就送入了prepareData.py处理。你看一下PEMS04_data.csv的格式，你写个脚本把03与07处理成这种格式。然后再把prepareData.py中的一些参数修改一下，就能得到了。

**Comment by wudi2001** [comment]
你可以再看看数据介绍.txt文件，里面有一些介绍。我印象中处理原始csv与npz数据脚本很简单，就没写最开始的那几步，核心步骤都写在prepareData.py中了。祝你能够尽快顺利中稿！！！

**Comment by OvOYu** [comment]
好的 ，感谢，我复现了下！！
